# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Prateek Jain
email: jainp@bu.edu
description: > 
  I am a creative and dynamic software engineer with 8+ years of experience in networking, software development, malware analysis, and VAPT. My expertise includes multiple programming languages and cybersecurity tools. I hold a Bachelor of Engineering in IT and pursuing an MS in Computer Science.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://prateekjain.tech" # the base hostname & protocol for your site
twitter_username: prateekjain
twitter:
  username: prateekjain
  card: summary
github_username:  prateekjain
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
# Build settings
markdown: kramdown
