# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Prateek Jain
email: jainp@bu.edu
description: > 
  I'm Prateek Jain, a computer science student pursing Master's from Boston University. As a full-stack developer, I have experience with C++, .NET Core, SQL Server, React, Java, and Angular. I've worked at Commvault Systems and Docyt, focusing on software engineering.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://prateekjain.tech" # the base hostname & protocol for your site
twitter_username: prateekjain
twitter:
  username: prateekjain
  card: summary
github_username:  prateekjain
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
# Build settings
markdown: kramdown
